### ISSUE TITLE
Wrong Windows 11 WNF Subscription Structs

### ISSUE THREAD

**Issue by oopsmishap** [daem0nc0re/SharpWnfSuite#1]
In Windows 11 the UserMode subscription structures were changed from using a linked list to a RB Tree. 

https://github.com/daem0nc0re/SharpWnfSuite/blob/ed0045605143cfce417781d99ab660b242d6f4e0/SharpWnfSuite/SharpWnfScan/Interop/Win32Struct.cs#L233

https://github.com/daem0nc0re/SharpWnfSuite/blob/ed0045605143cfce417781d99ab660b242d6f4e0/SharpWnfSuite/SharpWnfScan/Interop/Win32Struct.cs#L153

You will still get an output given the structure is not totally different but you will end up getting a tiny fraction of the WNF subscriptions as you will be only following the left nodes.

I wrote a tool a while ago similar to this in C++, I've just pushed it up onto github so you can use this as reference.

Below are the correct Windows 11 WNF Subscription structures:

* https://github.com/oopsmishap/wnfex/blob/63edfb63ad3b357ecd029f87b3b2626a8dbb6ca8/wnfex/wnf/wnf_structs.hpp#L108

* https://github.com/oopsmishap/wnfex/blob/63edfb63ad3b357ecd029f87b3b2626a8dbb6ca8/wnfex/wnf/wnf_structs.hpp#L124

Below are the RB Tree structures if you did not know them:

* https://github.com/oopsmishap/wnfex/blob/main/wnfex/win/win_structs.hpp#L23

Below is how to iterate the new structure as well as a helper class to iterate a RB Tree 

* https://github.com/oopsmishap/wnfex/blob/63edfb63ad3b357ecd029f87b3b2626a8dbb6ca8/wnfex/wnf/WnfSubscriberScan.cpp#L398

* https://github.com/oopsmishap/wnfex/blob/main/wnfex/util/RBTreeRemote.hpp

If I was a C# wizard I would just create a PR but alas I am not, I hope this helps.

**Comment by daem0nc0re** [comment]
I noticed the structures are changed but I did not have much time to investigate.
I will reflect your advice as soon as possible.
Thanks for your kindness 😃

**Comment by daem0nc0re** [comment]
Handled your issue.
Is this OK?
![SharpWnfScan-old](https://user-images.githubusercontent.com/33651482/169683877-57f2571b-94e2-4e1e-94ff-a83936301528.png)
![SharpWnfScan-new](https://user-images.githubusercontent.com/33651482/169683880-59aebb8f-ce16-46f0-9b92-4fa909c53394.png)

https://github.com/daem0nc0re/SharpWnfSuite/commit/11b3246164934d23575be6fbe4ab1ef495698c65

**Comment by daem0nc0re** [comment]
[Fixed coding mistake](https://github.com/daem0nc0re/SharpWnfSuite/commit/412c23c03300e985707a0611427028276333edb8).

**Comment by oopsmishap** [comment]
Looks good to me, I'm sure this will help wider WNF research in Windows 11

**Comment by daem0nc0re** [comment]
Thanks for your help!

**Comment by oopsmishap** [comment]
I made a little blog post about the thought process on finding it, I don't know if you want to put it under the articles or not but here it is: https://mishap.dev/posts/new-wnf-user-subscription-structures-in-w11/

**Comment by daem0nc0re** [comment]
Thanks 👍
